/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    java
    application
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("software.amazon.awscdk:aws-cdk-lib:2.138.0")
    implementation("org.apache.commons:commons-configuration2:2.11.0")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
    implementation(project(":lambda:stripe"))

    testImplementation("junit:junit:4.13.1")
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

application {
    mainClass = "com.myorg.AppApp"
}

tasks.withType<JavaExec>() {
    dependsOn(":lambda:stripe:assemble")
}